release.yml added

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,31 +1,57 @@
-# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
-# help make automated releases for this project
+name: Build and Publish
 
-name: Release
-
-on:
-  push:
-    branches:
-      - main
+on: [push, pull_request]
 
 jobs:
-  build-and-publish:
+  build:
     runs-on: ubuntu-latest
-    permissions:
-      # IMPORTANT: this permission is mandatory for trusted publishing
-      id-token: write
+
     steps:
-    - name: Checkout
+    - name: Checkout repository
       uses: actions/checkout@v3
+
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
-        python-version: '3.x'
-    - name: Install build dependencies
-      run: python -m pip install -U setuptools wheel build
-    - name: Build
-      run: python -m build .
-    - name: Publish
-      uses: pypa/gh-action-pypi-publish@release/v1
+        python-version: '3.x'  # Specify the Python version you need
+
+    - name: Install PDM
+      run: pip install pdm
+
+    - name: Cache PDM packages
+      uses: actions/cache@v3
       with:
-        skip-existing: true
+        path: ~/.pdm/cache
+        key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}
+        restore-keys: |
+          ${{ runner.os }}-pdm-
+
+    # - name: Verify pyproject.toml location
+    #   run: |
+    #     if [ ! -f pyproject.toml ]; then
+    #       echo "pyproject.toml not found in the root directory
+    #       exit 1
+    #     fi
+
+    # - name: Regenerate pdm.lock
+    #   run: pdm lock
+
+    - name: Install dependencies
+      run: pdm install
+
+    - name: Build the project
+      run: |
+        echo "Current directory: $(pwd)"
+        echo "Listing contents:"
+        ls -la
+        pdm build
+
+    - name: Verify the wheel
+      run: pdm info
+
+    - name: Upload distribution to GitHub Packages
+      if: github.event_name == 'push'
+      uses: actions/upload-artifact@v3
+      with:
+        name: dist
+        path: dist/*.whl
